### ISSUE TITLE
SBT libraryDependencies example is broken

### ISSUE THREAD

**Issue by subourbonite** [softwaremill/livestub#211]
This is a trivial issue, but the "stubbing from code" section of the readme contains the following example for adding livestub as a dependency:
`libraryDependencies += "com.softwaremill.sttp.livestub" % "livestub-sdk" % "0.1.18"`

This does not work as-written, due to not specifying the Scala version. It should be:
`libraryDependencies += "com.softwaremill.sttp.livestub" %% "livestub-sdk" % "0.1.18"`

**Comment by ghostbuster91** [comment]
Fixed in #299
